### ISSUE TITLE
u-boot-compulab won't build in r2.2

### ISSUE THREAD

**Issue by arrow53** [compulab-yokneam/meta-bsp-imx8mp#20]
@vraevsky I know it's not supported but was hoping to try out r2.2. I see this with a default  checkout / build. Any ideas?

```
x/u-boot-compulab/2022.04-r0/git/tools/mkeficapsule.c:21:10: fatal error: gnutls/gnutls.h: No such file or directory
|    21 | #include <gnutls/gnutls.h>
|       |          ^~~~~~~~~~~~~~~~~
| compilation terminated.
```

**Comment by arrow53** [comment]
need a package `sudo apt-get install libgnutls28-dev`
